### PR TITLE
Topic support

### PR DESCRIPTION
**Pull request by ehmkah**
- upgrade to gatling 3.4
- support topic-exchanges

### CODE REVIEW

**Comment by ehmkah** [comment]
@jigarkhwar => any news on this? We are really needing this feature :-)

**Comment by red-bashmak** [comment]
Hello Michael, i am checking your changes yet. Now i make some refactorings in CheckMaterializer and then check all together. If all ok, i merge and release new version.

**Review by red-bashmak — APPROVED** [review]
OK

**Comment by ehmkah** [comment]
Thank you for merging everything. :-) 

May I have a (for the moment) last wish? Would you be so kind and release a new version of the plugin?

**Pull request merged**
